---
# DESCRIPTION: Github actions config
#
# This file ONLY is placed under the Creative Commons Public Domain, for
# any use, without warranty, 2020 by Wilson Snyder.
# SPDX-License-Identifier: CC0-1.0

name: build-test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # weekly

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  vlt:
    runs-on: ubuntu-24.04
    name: build and test
    env:
      CI_OS_NAME: linux
      CI_RUNS_ON: ubuntu-24.04
      CI_COMMIT: ${{ github.sha }}
      CCACHE_COMPRESS: 1
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 4Gi
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Cache
        uses: actions/cache@v4
        env:
          cache-name: ccache
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages for build
        env:
          CI_BUILD_STAGE_NAME: build
        run: |
          echo "path-exclude /usr/share/doc/*"  | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
          echo "path-exclude /usr/share/man/*"  | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
          echo "path-exclude /usr/share/info/*" | sudo tee -a /etc/dpkg/dpkg.cfg.d/01_nodoc
          cd submodules/verilator && bash ci/ci-install.bash
          sudo cpan -fi Bit::Vector  # For t_cores_el2_cmark

      - name: CCACHE maintenance
        run: mkdir -p $CCACHE_DIR && cd submodules/verilator && bash ci/ci-ccache-maint.bash

      - name: Build
        env:
          CI_BUILD_STAGE_NAME: build
        run: cd submodules/verilator && bash ci/ci-script.bash

      - name: Save cache  # So faster to rerun if a test below fails
        uses: actions/cache/save@v4
        id: cache
        with:
          path: ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.ref }}-${{ github.sha }}

      - name: Install packages for tests
        env:
          CI_BUILD_STAGE_NAME: test
        run: |
          ( cd submodules/verilator && bash ci/ci-install.bash )
          python3 -m venv vl_venv
          source vl_venv/bin/activate
          pip install distro
          pip install submodules/astsee

      - name: Test
        run: |
          source vl_env/bin/activate
          export VERILATOR_ROOT=$GITHUB_WORKSPACE/submodules/verilator
          make test


      - name: Breakpoint if tests failed  FIXME FIXME
        if: failure()
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 30m
          authorized-users: wsnyder
